name: Handle contributor comment on GitHub issue

on:
  issue_comment:
    types: [created]

jobs:
  call-workflow:
    uses: Misha-s-Test-Organization/.github/.github/workflows/contributor-issue-comment.yml@bugfix
    secrets:
      LE_BOT_APP_ID: ${{ secrets.LE_BOT_APP_ID }}
      LE_BOT_PRIVATE_KEY: ${{ secrets.LE_BOT_PRIVATE_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_COMMUNITY_NOTIFICATIONS_WEBHOOK_URL: ${{ secrets.SLACK_COMMUNITY_NOTIFICATIONS_WEBHOOK_URL }}
